// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TakeAIMeal.Data
{
    // Receipes
    public class ReceipeConfiguration : IEntityTypeConfiguration<Receipe>
    {
        public void Configure(EntityTypeBuilder<Receipe> builder)
        {
            builder.ToTable("Receipes", "dbo");
            builder.HasKey(x => x.Id).HasName("PK__Receipes__3214EC07E8BBBFA7").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            builder.Property(x => x.MealType).HasColumnName(@"MealType").HasColumnType("int").IsRequired();
            builder.Property(x => x.ReceipeIdentifier).HasColumnName(@"ReceipeIdentifier").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.PictureIdentifier).HasColumnName(@"PictureIdentifier").HasColumnType("uniqueidentifier").IsRequired();

            builder.HasIndex(x => x.PictureIdentifier).HasDatabaseName("UQ__Receipes__07320BFE6C0A28FB").IsUnique();
            builder.HasIndex(x => x.ReceipeIdentifier).HasDatabaseName("UQ__Receipes__90378A230E88A036").IsUnique();
        }
    }

}
// </auto-generated>
