// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TakeAIMeal.Data
{
    // UserProductExclusionView
    public class UserProductExclusionViewConfiguration : IEntityTypeConfiguration<UserProductExclusionView>
    {
        public void Configure(EntityTypeBuilder<UserProductExclusionView> builder)
        {
            builder.ToView("UserProductExclusionView", "dbo");
            builder.HasNoKey();

            builder.Property(x => x.DietType).HasColumnName(@"DietType").HasColumnType("int").IsRequired();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("int").IsRequired();
            builder.Property(x => x.CategoryId).HasColumnName(@"CategoryId").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
