// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TakeAIMeal.Data
{
    // UserProductsExclusions
    public class UserProductsExclusionConfiguration : IEntityTypeConfiguration<UserProductsExclusion>
    {
        public void Configure(EntityTypeBuilder<UserProductsExclusion> builder)
        {
            builder.ToTable("UserProductsExclusions", "dbo");
            builder.HasKey(x => x.Id).HasName("PK__UserProd__3214EC073BBFAA00").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserDietId).HasColumnName(@"UserDietId").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Product).WithMany(b => b.UserProductsExclusions).HasForeignKey(c => c.ProductId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__UserProdu__Produ__06CD04F7");
            builder.HasOne(a => a.UserDiet).WithMany(b => b.UserProductsExclusions).HasForeignKey(c => c.UserDietId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__UserProdu__UserD__05D8E0BE");
        }
    }

}
// </auto-generated>
