// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TakeAIMeal.Data
{
    // UserDiets
    public class UserDietConfiguration : IEntityTypeConfiguration<UserDiet>
    {
        public void Configure(EntityTypeBuilder<UserDiet> builder)
        {
            builder.ToTable("UserDiets", "dbo");
            builder.HasKey(x => x.Id).HasName("PK__UserDiet__3214EC07B46E7C20").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            builder.Property(x => x.DietType).HasColumnName(@"DietType").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
