//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeAIMeal.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakeAIMeal.Common.Resources.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a title for dish based on this ingredients :  {0}.
        /// </summary>
        public static string DishTitleFromTags {
            get {
                return ResourceManager.GetString("DishTitleFromTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a recipe for a {1} using this ingredients : {0}.
        /// </summary>
        public static string RecipeFromIngredients {
            get {
                return ResourceManager.GetString("RecipeFromIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a recipe for a {1} using these ingredients : {0}. Recipe has to match for diet {2}..
        /// </summary>
        public static string RecipeFromIngredientsWithDiet {
            get {
                return ResourceManager.GetString("RecipeFromIngredientsWithDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a recipe for a {1} using these ingredients : {0}. Recipe has to match for diet {2} and can not included this ingredients : {3}.
        /// </summary>
        public static string RecipeFromIngredientsWithDietAndExclusions {
            get {
                return ResourceManager.GetString("RecipeFromIngredientsWithDietAndExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a random recipe for a {0}..
        /// </summary>
        public static string RecipeRandomForMeal {
            get {
                return ResourceManager.GetString("RecipeRandomForMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate one short tip about healthy eating..
        /// </summary>
        public static string TipHealthyEating {
            get {
                return ResourceManager.GetString("TipHealthyEating", resourceCulture);
            }
        }
    }
}
