// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace TakeAIMeal.Data
{
    public class TakeAIMealDbContextFactory : IDesignTimeDbContextFactory<TakeAIMealDbContext>
    {
        public TakeAIMealDbContext CreateDbContext(string[] args)
        {
            return new TakeAIMealDbContext();
        }
    }
}
// </auto-generated>
