// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TakeAIMeal.Data
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // GeneratedRecipes
    public class GeneratedRecipe
    {
        public int Id { get; set; } // Id (Primary key)
        public DateTime? Date { get; set; } // Date
        public int MealType { get; set; } // MealType
        public int? UserId { get; set; } // UserId
        public int RecipeType { get; set; } // RecipeType

        public GeneratedRecipe()
        {
            Date = DateTime.Now;
            RecipeType = 1;
        }
    }

}
// </auto-generated>
