// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TakeAIMeal.Data
{
    // ProductCategories
    public class ProductCategory
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child Products where [Products].[CategoryId] point to this entity (FK__Products__Category__7D439ABD)
        /// </summary>
        public ICollection<Product> Products { get; set; } // Products.FK__Products__Category__7D439ABD

        public ProductCategory()
        {
            Products = new List<Product>();
        }
    }

}
// </auto-generated>
