// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TakeAIMeal.Data
{
    // Receipes
    public class Receipe
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int MealType { get; set; } // MealType
        public Guid ReceipeIdentifier { get; set; } // ReceipeIdentifier
        public Guid PictureIdentifier { get; set; } // PictureIdentifier
    }

}
// </auto-generated>
