// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TakeAIMeal.Data
{
    // Recipes
    public class Recipe
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int MealType { get; set; } // MealType
        public Guid RecipeIdentifier { get; set; } // RecipeIdentifier
    }

}
// </auto-generated>
