// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace TakeAIMeal.Data
{
    public class SpHelpdiagramsReturnModel
    {
        public string Database { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public string Owner { get; set; }
        public int OwnerID { get; set; }
    }

}
// </auto-generated>
