// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace TakeAIMeal.Data
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class SpHelpdiagramdefinitionReturnModel
    {
        public int? version { get; set; }
        public byte[] definition { get; set; }
    }

}
// </auto-generated>
