// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TakeAIMeal.Data
{
    // UserProductsExclusions
    public class UserProductsExclusion
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserDietId { get; set; } // UserDietId
        public int ProductId { get; set; } // ProductId

        // Foreign keys

        /// <summary>
        /// Parent Product pointed by [UserProductsExclusions].([ProductId]) (FK__UserProdu__Produ__06CD04F7)
        /// </summary>
        public Product Product { get; set; } // FK__UserProdu__Produ__06CD04F7

        /// <summary>
        /// Parent UserDiet pointed by [UserProductsExclusions].([UserDietId]) (FK__UserProdu__UserD__05D8E0BE)
        /// </summary>
        public UserDiet UserDiet { get; set; } // FK__UserProdu__UserD__05D8E0BE
    }

}
// </auto-generated>
