// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TakeAIMeal.Data
{
    // UserDiets
    public class UserDiet
    {
        public int Id { get; set; } // Id (Primary key)
        public string UserId { get; set; } // UserId (length: 450)
        public int DietType { get; set; } // DietType

        // Reverse navigation

        /// <summary>
        /// Child UserProductsExclusions where [UserProductsExclusions].[UserDietId] point to this entity (FK__UserProdu__UserD__05D8E0BE)
        /// </summary>
        public ICollection<UserProductsExclusion> UserProductsExclusions { get; set; } // UserProductsExclusions.FK__UserProdu__UserD__05D8E0BE

        public UserDiet()
        {
            UserProductsExclusions = new List<UserProductsExclusion>();
        }
    }

}
// </auto-generated>
