// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace TakeAIMeal.Data
{
    // UserProductExclusionView
    public class UserProductExclusionView
    {
        public int DietType { get; set; } // DietType
        public int UserId { get; set; } // UserId
        public int ProductId { get; set; } // ProductId
        public int CategoryId { get; set; } // CategoryId
    }

}
// </auto-generated>
